var GAME_LEVELS = [

  ["                                                                                ",
   "                                   w         w   xxxx o                   w     ",
   "           w      w                       w     xxxxxx          w               ",
   "             w                                 xxxxxxxx                         ",
   "                                               x      x                      x  ",
   "                            o                     oo                         x  ",
   "                                                                             x  ",
   "  xx                o     xxxxx     o                      x                 x  ",
   "  x                       x   x                            xx                x  ",
   "  x         o     xxxxx   x   x   xxxxx     o              xxx               x  ",
   "  x                 x     x   x   x   x                    xxxx              x  ",
   "  x       xxxxx     x     xxxxx   x   x   xxxxx            xxxxx       o     x  ",
   "  x       x         x     x   x   x   x     x     xxxxxxxxxxyxyxx            xxx",
   "  x @     x         x     x   x   xxxxx     x     xxxxxxxxxxyxyxxx     x        ",
   "  xxxxx   x         x     x   x   xx        x     xxxxxxxxxxxxxxxxx   xx      o ",
   "      x   xxxxx     x     x   x   x x       x     xxxxxxxxxyxxxyxx    xxx       ",
   "      x       x     x             x  x      x     xxxxxxxxxxyyyxx     xxx   xxxx",
   "      x!!!!!!!x!!!!!x!!!!!!!!!!!!!x!!!x!!!!!x!!!!!!!!!!!!!!xxxxx!!!!!xxxx!!!x   ",
   "      x!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!xxxx!!!!!!xxxx!!!x   ",
   "      x!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!xxx!!!!!!!xxxxx!!x   ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!xxxxxxx!x   ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                                ",
   "                                                                                "],

   ["                                                                                                              ",
    " o       o         o         o       o       o         ooooo       o       ooooo     o                        ",
    " o      oo        oo        oo      ooo      oo         oooo      ooo       oooo     oo                       ",
    " o     ooo       ooo       ooo     ooooo     ooo         ooo     ooooo       ooo     ooo                      ",
    " o      oo        oo        oo      ooo      oooo         oo      ooo         oo     oooo                     ",
    " o       o         o         o       o       ooooo         o       o           o     ooooo                    ",
    "                                                                                                              ",
    "                                                                                                              ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
    "                                      =                                                                       ",
    "                                                                                                     =        ",
    "                          =                                                                    =             x",
    "                                                                                                              ",
    "              =                                                                    =                          ",
    "                 o                       o                       o                       o                    ",
    "  =                                                                    =                                      ",
    "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                    ||                        ",
    "                ||o ||                       || o  ||                               o                         ",
    "x             ||      ||                  ||          ||                      ||          ||                  ",
    "            ||          ||             ||                ||                                                   ",
    "          ||              ||        ||                      ||          ||                      ||            ",
    "        ||                  ||                                                                                ",
    "                                                                  ||                                  ||      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
    "                               v           v           v                                                      ",
    "                                                                                                              ",
    "                                                                                                             x",
    "                                                                                                              ",
    "                                                                                                              ",
    "             o                          o     o                                                               ",
    " @                                                    x      e           e         e         e           e    ",
    "xxx     xx   x   xx     xxxxxxxxx   xxxxxx   xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

   ["                                                                                                                  ",
    "                                                                                                   xxxxx          ",
    "                                                                       w                           x    x         ",
    "                          xxxxxxx                             x                                    x  w  x        ",
    "                          x!!!!!x                             x                                    x     x        ",
    "                          x!!!!!x                             x                                    x    x         ",
    "                          x!!!!!x                             x                                    xxxxx       w  ",
    "                          xxx!xxx                             x  o        xxxxxxxxxx                              ",
    "                            x!x          w                    x                     x             xxxxxxx         ",
    "                            xvx                               xxxxxx                 x  o         x     x         ",
    "                      w                          o                 x                 xx           x     x         ",
    "                                                                   x                 x xxx        x  w  x         ",
    "                                               xxxxxx          w   xxxxxxx     xxx   x            x     x         ",
    "                                                     x                       o x     x  w       o xxxxxxx         ",
    "        @                     w            o          x          w             x     x                            ",
    "        x                                              x                    xxxx     x w        x     x       w   ",
    "        x        o   xxx    xxx                         x                   x        x          x     x           ",
    "       xxx             x    xyx         xxxxx       xxxxxx                  x        x         xx     x           ",
    "       xxx       x     x  o xxx                           x              xxxx        x          x  x  x   w       ",
    "      xxxx      xx     x                                   x            x            x          x x x x           ",
    "     xx!!xx     xxx    x                       xxx          x    o     x             x  o       xx   xx           ",
    "     xx!!!xx   xxxx    xxxxxxxxxxxxx           x       w     xe       x              x        p                   ",
    "     xx!!!!xx  xxxx                x          xx   w          xxxxxxxx               xxxxxx   xx    x             ",
    "    xx!!!!!xx xx!xx                x           x                                              x x   x             ",
    "   xxx!!!!!xxxx!!!xx               x     o     x                                              x  x  x             ",
    "  xx!!!!!!!xxx!!!!!xx!!!!!!!!!!!!!!xx          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!x!x!!!!!!!!!!!!!",
    "  xx!!!!!!!xx!!!!!!!xx!!!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!xx!!!!!!!!!!!!!",
    "  xx!!!!!!!!xx!!!!!!xx!!!!!!!!!!!!!x!!!xx!!xx!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!x!!!!!!!!!!!!!",
    " xx!!!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "xx!!!!!!!!!!!xx!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

    ["                                                                                                              ",
     "                                                                                                              ",
     "   xxxx                              o   r                                                                    ",
     "   x                                                                                                   xx     ",
     "   x                         xxxxxxxxxxxxxxxxx                                                        xxx     ",
     "   x @                       x!!!!!!!!!!!!!!!x              x                    x                   xxx      ",
     "   xxxxx   xxxxx             x!!!!!!!!!!!!!!!x             x   x      xx      x   x                 xxx       ",
     "   !!!!x   x   x             xxxx!xxxxxxx!xxxx             x  x      xxxx      x  x             o  xxx        ",
     "  !!!!!x   x   x                x!x     x!x       xxxx     x  x  o  xxxxxx  o  x  x      o        xxx         ",
     " !!!!!!x   x   x                xvx     x!x                x   x     xxxx     x   x xxx      x   xxx          ",
     "!!!!xxxx   xxxxx   xxxxx                x!x            o    x   xxx   xx   xxx   x           xx xxx           ",
     "!!!        x         x                  x!x                  xx  xxxxxxxxxxxx  xx            xxxxx            ",
     "!!!        x         x                  xvx           xxx     xx xxxyyyyyyxxx xx             xxxx             ",
     "!!         x         x                                         xxxxxxyyyyxxxxxx           xx xxxxx            ",
     "!!         x         x                                         xx xxxxyyxxxx xx              xxxxxx           ",
     "!!!                  x     xxx                               xx   xxxyyyyxxx   xx                             ",
     "!!!                  x o   x  x                 xxx         xx   x xyyyyyyx x   xx  xxx                       ",
     " !!!                 x     x   x                        o   x    x xxxxxxxx x    x                            ",
     "  !!               xxxxx   x   x                            x   x    xxxx    x   x                            ",
     "  !!                       x   x                       xxx  x   x            x   x                            ",
     "  vv                       x   x   xxxxx                    x   x o        o x   x    xxx                     ",
     "                           x   x   x                             x          x                                 ",
     "!                          x  x    x o                            x        x                 x                ",
     "!!                         xxx     x              xxx                                       xx                ",
     "!!!     xxx                        xxx     xxxxx                                             x                ",
     "!!!!                               x       x   x                     xxx                     x                ",
     "!!!!!                              x o     x   x                       x                     x                ",
     "!!!!!!          xxx                x       x   x                       x                     x     !!!!!!     ",
     "!!!!!!!!                           xxxxx   xxxxx                       xxxxxxxx   xxxxxxxxxxxx   !!!!!!!!!!   ",
     "!!!!!!!!!!                                 xx                                 x   x             !!!!!!!!!!!!  ",
     "!!!!!!!!!!!!!           xxx               xx x                                x o x            !!!   !!!!!!!! ",
     "!!!!!!!!!!!!!!!!!                          x  x                               x  xx            !!     !!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!                      x   x                              x   x            !       !!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!     xxx                                        xxxx                    o   !!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       xxxxx                                x    o                      !!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                         x           e           x  !!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                  xxxxxxxxxxxxxxxxxxxxxxxxx !!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                   !!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                           !!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                 !!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       !!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!              !!!!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

     ["               v                                             ",
      "         v           v                                       ",
      "   vyyyyy yyyyy yyyyy yyy  v                                 ",
      "    y     y   y y   y y  y                                   ",
      "    y     y   y y   y y   y                                  ",
      "    y  yy y   y y   y y   y                                  ",
      "    y   y y @ y y   y y  y                                   ",
      "    yyyyy yyyyy yyyyy yyy                                    ",
      "                                                             ",
      "                                                             ",
      "    yyyyy yyyyy y   y yyyyy                                  ",
      "    y     y   y yy yy y                                      ",
      "    y     y   y y y y yyyy                                   ",
      "    y  yy yyyyy y   y y                                      ",
      "    y   y y   y y   y y                                      ",
      "    yyyyy y   y y   y yyyyy                                  ",
      "                                                             ",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
